typesense.org/docs/0.14.0/guide.html
When I installed Typesense via the DEB, the config was at `/etc/typesense/typesense-server.ini` as opposed to `/etc/typesense/typesense.ini`. This is also what it says further down in the guide.
I only tested 0.14, so not sure if this also applies to the older versions.
=> Correct config path in getting started guide

typesense.org/_config.yml
First of all, thank you for version 0.17.0!
Did you know that https://typesense.org/docs/0.17.0/guide is 404-ing? https://typesense.org/docs/0.17.0/guide.html, however, is not.
I couldn't replicate this in the local development environment, but I did notice the `permalink` configuration from `_config.yml` was missing for this version. I have added that in this PR. Is it being used to generate redirects?
=> Add missing permalink for docs/0.17.0

typesense.org/docs/0.18.0/api.html
The search response in v0.18 differs from what's mentioned in the docs. This PR updates the docs to reflect the current API response.
close https://github.com/typesense/typesense/issues/194
=> Update search response

typesense.org/docs/0.18.0/api.html
Add a mention that a document `id` cannot include spaces or any other characters that are encoded in URLs, as using those characters in an `id` can cause issues.
close https://github.com/typesense/typesense/issues/192
Note: I've previously signed the CLA. I assume that's enough and I don't need to submit it again, but if required, I will.
=> Update api reference to include id restrictions

typesense.org/docs/0.18.0/api.html
There was a comma missing after `'apiKey': '<API_KEY>'`. See below.
```js
let client = new Typesense.Client({
'nodes': [{
'host': 'localhost',
'port': '8108',
'protocol': 'http',
}],
'apiKey': '<API_KEY>'
'connectionTimeoutSeconds': 2
})
```
close https://github.com/typesense/typesense/issues/211
=> Fix JS Client authentication typo -- missing comma

typesense.org/docs/0.19.0/guide.html
Adds a section for updating Typesense to the guides page of the docs.
Close https://github.com/typesense/typesense-website/issues/42
- [ x ] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).
=> Add "Updating Typesense" section to guides page

docs-site/content/0.13.0/guide/typesense-firebase.md, docs-site/content/0.16.0/guide/firebase-full-text-search.md, docs-site/content/0.16.1/guide/firebase-full-text-search.md, docs-site/content/0.17.0/guide/firebase-full-text-search.md, docs-site/content/0.18.0/guide/firebase-full-text-search.md, docs-site/content/0.19.0/guide/firebase-full-text-search.md, docs-site/content/0.20.0/guide/firebase-full-text-search.md
Removes "originally" in the description of instantsearch.
While according to the license, it's completely fine to refer to instantsearch as "made by algolia" and using an adapter for typesense, mentioning it's "originally" made by Algolia, while there's no modifications done by Typesense is slightly confusing IMO.
note: i'm not making this PR from the POV of Algolia legal, just as one of the developers on the project.
=> chore(instantsearch): clarify ownership

docs-site/content/0.20.0/api/api-keys.md
Looks like it was already fixed for the other languages, but the copied text from the section above remained for javascript.
=> docs: fix search-only api key description for js

docs-site/content/0.20.0/api/api-keys.md, docs-site/content/0.20.0/api/authentication.md, docs-site/content/0.20.0/api/cluster-operations.md, docs-site/content/0.20.0/api/collection-alias.md, docs-site/content/0.20.0/api/collections.md, docs-site/content/0.20.0/api/curation.md, docs-site/content/0.20.0/api/documents.md, docs-site/content/0.20.0/api/synonyms.md, docs-site/content/0.21.0/api/api-keys.md, docs-site/content/0.21.0/api/authentication.md, docs-site/content/0.21.0/api/cluster-operations.md, docs-site/content/0.21.0/api/collection-alias.md, docs-site/content/0.21.0/api/collections.md, docs-site/content/0.21.0/api/curation.md, docs-site/content/0.21.0/api/documents.md, docs-site/content/0.21.0/api/synonyms.md
Last remaining steps:
CC: @happy-san Feel free to edit
=> Publish Dart Examples

docs-site/content/0.21.0/guide/install-typesense.md
wget is not installed by default on macOS.
I realize most developers could figure out what to do with the instructions as is, but I can tell you at Typesense care about getting the small details right.
wget is not installed by default on macOS.
I realize most developers could figure out what to do with the instructions as is, but I can tell you at Typesense care about getting the small details right.
=> Change Mac download instructions to use curl

docs-site/content/guide/building-a-search-application.md
explode PHP_EOL should be used.
json_decode by default use object but create() function need array so true flag to make an associative array
=> explode & json_decode is not correct

docs-site/content/guide/docsearch.md
I was having some trouble debugging the CSS on the docsearch UI, but after reading the code, I found that there was a debug init option that solved my issue. 
I thought this knowledge would make a great addition to the docs.
=> added docs about how to debug css on devtools

docs-site/content/0.19.0/api/synonyms.md, docs-site/content/0.20.0/api/synonyms.md, docs-site/content/0.21.0/api/synonyms.md
Hi,
Corrected
```bash
curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" "http://localhost:8108/collections/products/synonyms"
```
To
```bash
curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" "http://localhost:8108/collections/products/synonyms/coat-synonyms"
```
This was done to follow the spec `GET ${TYPESENSE_HOST}/collections/:collection/synonyms/:id`
=> correct example retrieve synonym shell

docs-site/content/0.22.1/api/documents.md
Makes clear that one has to use the correct order of coordinates for geopoints, since the underlying library will throw an error If the latitude is not between -90 and 90 degrees inclusive
or the longitude is not between -180 and 180 degrees inclusive.
Minor changes in the documents.md of 0.22.1
=> Update documents doc site

docs-site/content/0.22.1/api/api-clients.md, docs-site/content/0.22.1/api/api-keys.md, docs-site/content/0.22.1/api/authentication.md, docs-site/content/0.22.1/api/cluster-operations.md, docs-site/content/0.22.1/api/collection-alias.md, docs-site/content/0.22.1/api/collections.md, docs-site/content/0.22.1/api/documents.md, docs-site/content/0.22.1/api/synonyms.md
- Installation / Authentication
- Collections
- Documents
- ApiKeys
- Synonyms
- Aliases
- Cluster Operations
- Fixed a tiny mistake in Java one-way synonym caption
- Curations
- Geosearch
- Multisearch
- Batch-size while importing
- Dealing with dirty data
- Scoped search key
=> Add Swift Client to Documentation

docs-site/content/0.22.1/api/cluster-operations.md
using `0.22.1` and calling `/health` on the server, the json response I'm getting doesn't match what's in doc.
This updates doc to what i'm getting.
running `typesense-server-0.22.1-darwin-amd64/typesense-server`
screenshot of what i'm getting from wireshark:
=> Update server /health response doc example

docs-site/content/guide/docsearch.md
Updated documentation to add in instructions for adding DocSearch meta tags to the schema.
=> Add in documentation on adding custom DocSearch meta tags

docs-site/content/guide/docsearch.md
=> Fix typo in DocSearch guide

docs-site/content/guide/install-typesense.md
The config, data and logging directory for the Homebrew installation are incorrect/outdated. I just did a clean install on my M1 Macbook Pro and this is where they ended up.
Update the config, logging and data directory for the Homebrew installation of Typesense on Mac..
=> Update install-typesense.md to correct Homebrew config, data and logging directory

docs-site/content/0.23.1/api/search.md
The example is meant to have a string field with the sort enabled. Currently the field with sorting turned on shows int32 as the type.
=> Typo in Search documentation

docs-site/content/0.23.1/api/collections.md
`"index": false` also requires ` "optional": true` to work in v0.23.1. 
Otherwise, collection creation will fail with:
`{ "message": "Field <field name> must be optional since it is marked as non-indexable." }` 
Relates to https://github.com/typesense/typesense/issues/721
Describing above situation in the doc.
=> Fix doc for field exclusion from indexing

docs-site/content/0.23.1/api/api-keys.md
As discussed in [this slack thread](https://typesense-community.slack.com/archives/C01P749MET0/p1673312851871479)  `create` doesn't exist as an action/http method, however `upsert` (PUT) does.
This PR updates the API Key permissions section to reflect that.
Please note I have confirmed that `upsert` works (using the docsearch scraper) but I haven't personally verified that `create` doesn't exist. The removal of `create` is based purely on the slack conversation.
=> remove create and add upsert for alias key permissions

docs-site/content/guide/reference-implementations/xkcd-search.md
Typo error on [typesense/../../xkcd-search.html](https://typesense.org/docs/guide/reference-implementations/xkcd-search.html). Refers `xkcd` as `books` in the headline.
=> typo: `xkcd search` page refered as `books search`

typesense.org/components/Home/SectionShowcase.vue
Nothing to see here, just fixing a typo 🤠 🛠️
`xckd` -> `xkcd`
=> Fix xkcd typo on homepage

docs-site/content/.vuepress/config.js, docs-site/content/guide/supabase-full-text-search.md
I added a section to the guide section for Typesense that discusses strategies to sync Typesense with Supabase. The documentation is fairly thorough and should be a decent reference for anyone trying to connect Typesense to a PostgreSQL instance.
=> Added a Supabase-full-text-search guide for Typesense

docs-site/content/guide/building-a-search-application.md
I'm working with Typesense in Node, and was following this doc. TypeScript throws a type error, since the type of `port` is `number`, not `string`. I didn't check the other libraries for other languages, but it seems likely the same issue will exist elsewhere.
=> Fix "Build A Search Application" docs: "port" is a number, not string

typesense.org/pages/typesense-vs-algolia-vs-elasticsearch-vs-meilisearch.vue
MeiliSearch is currently limited to only supporting one `_geo` field per document and searching on it.
Although it's a [highly requested feature](https://github.com/meilisearch/product/discussions/508), there's currently no official plans to support multiple geo points and search. This can be a pretty substantial limitation for those that need the feature, so it's worth documenting.
=> Update Geo Search to show Geo Search limitation for MeiliSearch

docs-site/content/0.25.1/api/documents.md
Fixed the "Update by query" code example's collection reference from "comapnies" to "companies"
=> Typo fix to documents.md

docs-site/content/0.25.1/api/api-keys.md
Incorporate the omitted `stats.json:list` action for API key permissions. After testing, it appears that this action has already been implemented.
=> API key permissions documentation update: Add stats.json:list Action

docs-site/content/guide/docsearch.md
Add a `tip` block related to how to customize your `config.json` file to be right handled by the DocSearch scraper.
It's related to this issue: https://github.com/typesense/typesense-docsearch-scraper/issues/49
=> Improve DocSearch docs related to running scraper inside docker

docs-site/content/guide/supabase-full-text-search.md
Updated function signature to match current version of pg_net
PG_NET no longer supports the  `net._http_collect_response(<request_id>);` function. Removed it
- [ x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).
=> Updated supabase-full-text-search.md | updated pg_net reference

docs-site/content/guide/reference-implementations/laravel-scout-integration.md
Documentation link to Laravel is (slightly) outdated. 
Laravel released new current version. Leaving out the version from the url performs a redirect to current version which likely wont need updating
=> Update reference to laravel documentation

docs-site/content/guide/github-actions.md
Basically we can write e2e tests without relying on another Github actions package like [`jirevwe/typesense-github-action@v1.0.1`](https://github.com/marketplace/actions/typesense-server-in-github-actions). Just purely relying on containers.
- Proof of workflow action that passed the test: https://github.com/jaeyson/ex_typesense/actions/runs/9212348923/job/25343766747
- Link to the example file: https://github.com/jaeyson/ex_typesense/blob/main/.github/workflows/ci.yml
The main gist is to add a service container then `docker run...`
```yaml
...
strategy:
matrix:
typesense-version: ['0.25.2', '26.0']
typesense-port: ['8108:8108']
...
services:
typesense:
image: typesense/typesense:${{ matrix.typesense-version }}
steps:
- name: Checkout repo
uses: actions/checkout@v4
- name: Start Typesense …
```
=> Remove additional dependency when using Github actions for e2e tests.

docs-site/content/26.0/api/joins.md
This PR introduces a simpler example for one-to-many relations in the JOINs documentation. The initial example provided was a bit complex as it showcased a link table, which might be confusing for readers initially. 
The new example aims to break down the concept into more digestible parts, making it easier for users to grasp the basic idea of joins. It focuses on a straightforward one-to-many relationship, without the added complexity of a link table.
=> Simplify One-to-Many Relations Example in JOINs Documentation

docs-site/content/0.25.2/api/api-clients.md, docs-site/content/26.0/api/api-clients.md, docs-site/content/guide/reference-implementations/laravel-scout-integration.md, typesense.org/components/Footer.vue, typesense.org/components/Home/SectionAPILibraries.vue
The current version of the Laravel docs are for v11. Update the links to the Typesense section there.
=> Update Laravel docs links to the current version (v11)

docs-site/content/26.0/api/collections.md
This change adds an important warning to the collections API documentation for Typesense v26.0. It informs users about a new restriction on concurrent alter operations, which was implemented to address client timeout issues. 
- Added a warning block to highlight a new limitation in v26.0
=> docs(collection): add warning about concurrent alter operations in v26.0

docs-site/content/26.0/api/collections.md
The documentation now explicitly states that dropping a field only affects 
the schema and in-memory index, without deleting the field's data from existing 
documents stored on disk. Instructions to permanently remove field data have 
also been included.
=> docs(collections): add clarification on field removal by update

docs-site/content/26.0/api/conversational-search-rag.md
- Added a warning about breaking changes in Conversational Search (RAG) in version 27.
- Advised users to ensure they are using the latest version of Typesense.
- Removed Updating model section as it wasn't included in v26
=> docs(rag): update conversational search API docs for v27 changes

docs-site/content/27.0/api/vector-search.md, docs-site/content/guide/semantic-search.md
- Introduce `k` parameter usage in vector queries for pagination
- Demonstrate `distance_threshold` parameter for result tuning
- Include code examples for both parameters in curl requests
- Guide readers of guide page to API documentation by a link
=> docs(vector-search): add pagination guidance for vector search

docs-site/content/26.0/api/search.md, docs-site/content/27.0/api/search.md
Fixed a typo from `groping` to `grouping`
=> fix: typo on grouping parameter link

docs-site/content/27.1/api/server-configuration.md
- Document new server parameter for controlling the rate limit of analytics events. This parameter allows users to adjust the maximum number of events that can be sent per minute, addressing issues with event rate limiting in high-traffic scenarios.
Resolves https://github.com/typesense/typesense/issues/1980
=> docs(server-config): add analytics-minute-rate-limit server parameter

docs-site/content/27.1/api/search.md
This adds a more complicated example for combining filters in _eval() statements, to boost matches that meet certain criteria.
=> Add example for combining filter clauses inside _eval() statements

docs-site/content/27.1/api/api-keys.md
Add three simple tables on the API Key documentation for documenting all available actions  for analytics, analytics rules, and analytics events.
Documentation updates:
* [`docs-site/content/27.1/api/api-keys.md`](diffhunk://#diff-a69f54deb53683cc23f5a853943ed632f97a58e27116acd0f889d7db64fb56deR362-R387): Added sections for `Analytics actions`, `Analytics Rules actions`, and `Analytics Events actions` with corresponding permissions and descriptions.
=> docs(keys): add tables for analytic actions for api keys

docs-site/content/guide/tips-for-filtering.md
The `![]` operator isn't valid, the correct one should be `!=[]`
=> fix(filter-guide): fix NOT part of operator from `![]` to `!=[]`

docs-site/content/27.0/api/vector-search.md, docs-site/content/27.1/api/vector-search.md, docs-site/content/guide/semantic-search.md
A documentation fix that corrects the vector query syntax examples throughout our guides. The correct syntax requires a colon (`:`) after the field name in vector queries, ensuring users can properly implement vector search functionality in their applications.
1. **In `docs-site/content/27.0/api/vector-search.md` and `27.1/api/vector-search.md`**:
- Updated vector query syntax from `embedding([], k: 200)` to `embedding:([], k: 200)`
- Fixed examples in pagination section
2. **In `docs-site/content/guide/semantic-search.md`**:
- Updated vector query examples to use correct syntax
- Fixed vector query syntax in both basic and threshold examples
- Examples updated:
- Basic vector query: `embedding:([], k: 200)`
- Vector query with threshold: `embedding:([], k: 200, distance_threshold: 1.0)` …
=> Fix vector query syntax in documentation

docs-site/content/.vuepress/config.js, docs-site/content/guide/testcontainers.md
Testcontainers is a library used to run containers as part of your tests
in your preferred programming language.
This documentation uses the new module provided by Testcontainers for Java.
See #282
=> Add Testcontainers docs

docs-site/content/27.1/api/vector-search.md
As visible [here](https://github.com/typesense/typesense/blob/8cdd3101ecd31da80acf388bc72005be60ec4512/src/embedder_manager.cpp#L532) in `embedder_manager.cpp`, remote endpoints are expected to have a model name which starts with one of  `openai/`, `google/` or  `gcp/`.
This prefix [is removed](https://github.com/typesense/typesense/blob/98dfb5b686b7d46620f35af36986698563bd908f/src/text_embedder_remote.cpp#L102) slightly later on in the execution of the program when running an OpenAI compatible endpoint.
The documentation doesn't make it clear that OpenAI-compatible endpoints have to start with "openai" in the model name, so, I've added that fact in.
=> OpenAI compatible endpoints require model name starts with `openai`.

docs-site/content/guide/docsearch.md
Adds a section for the latest feature implemented in https://github.com/typesense/typesense-docsearch-scraper/pull/76
=> docs(scraper): add custom headers configuration for docsearch scraper

docs-site/content/28.0/api/stemming.md
This pull request includes changes to the `docs-site/content/28.0/api/stemming.md` file to correct the API endpoint for stemming dictionaries.
Documentation updates:
* [`docs-site/content/28.0/api/stemming.md`](diffhunk://#diff-3e4dfadbc24bb85890c32599a364e55f90e518dddf5a685db8f2b6845827054cL68-R68): Changed the endpoint from `/stemming/dictionary/` to `/stemming/dictionaries/` in two instances to reflect the correct API usage
=> fix(stemming): fix stemming endpoint paths in examples

docs-site/content/28.0/api/analytics-query-suggestions.md
Addresses #291 
**Changes to rule names and configurations:**
* Updated Ruby example rule name from `'popular_queries'` to `'product_queries_aggregation'` and `'product_no_hits'` (`client.analytics.rules().upsert(ruleName, ruleConfiguration)`) 
* Updated JavaScript example rule name from `'product_queries_aggregation'` to `'product_no_hits'` (`aggregated in 'no_hits_queries' collection.`).
* Updated JavaScript example rule name from `'product_queries_aggregation'` to `'product_clicks'` (`Let's define a 'counter' analytics rule that will increment this field whenever`).
* Updated Ruby example rule name from `'popular_queries'` to `'product_clicks'` (`client.analytics.rules().upsert(ruleName, ruleConfiguration)`).
* Updated cURL example rule name from `'products_popularity'` to …
=> fix(docs): unify analytics rule names across code examples

docs-site/content/guide/laravel-full-text-search.md
This pull request includes a small but important change to the `docs-site/content/guide/laravel-full-text-search.md` file. The change adds a warning to remind users to import their model at the top of the `config.php` file, which is essential for the `model-settings` to work.
Documentation update:
* [`docs-site/content/guide/laravel-full-text-search.md`](diffhunk://#diff-ae2706c19edacdf71bd9f872b705c1bb5e154d10f8092895df17b0f7e2e876b5R599-R602): Added a warning to import the model using `use App\Models\Game;` at the top of the `config.php` file.
=> fix(laravel-guide): add warning for model imports on scout guide

docs-site/content/28.0/api/vector-search.md
This pull request includes an update to the documentation related to vector search in the `docs-site/content/28.0/api/vector-search.md` file. The update adds a tip about embedding updates to clarify when embeddings are regenerated.
Documentation update:
* Added a tip to explain that embeddings are only regenerated when fields specified in the `embed.from` configuration are updated, which helps avoid unnecessary embedding recreation and API calls. (`docs-site/content/28.0/api/vector-search.md`)
=> docs: add tip about embedding regeneration behavior

docs-site/content/28.0/api/joins.md
This pull request includes an update to the documentation for the `joins` API. The change introduces the concept of asynchronous references, which allows documents to be indexed even if the referenced document does not yet exist.
Documentation update:
* [`docs-site/content/28.0/api/joins.md`](diffhunk://#diff-cc6885ad44ade85ad49c6e9e6e9ec675565ce1444ae89c181a01c8d449e0b877R446-R465): Added a section on asynchronous references, including an example JSON configuration and an explanation of how `async_reference` works to prevent indexing errors when referenced documents are not yet available.
=> feat(docs): add async_reference option to joins documentation

docs-site/content/.vuepress/components/VersionDropdown.vue
Maintains user's position in docs when switching between different Typesense versions. Closes #188
1. **In `VersionDropdown.vue`**:
- Modified the [warning message](diffhunk://#diff-8ed94555eb24b9ab6404a3aab081d222da017446d39cf031cd367343b9730dd5L17-R19) to use the new `getVersionedPath` method for generating versioned paths
- Added [computed properties](diffhunk://#diff-8ed94555eb24b9ab6404a3aab081d222da017446d39cf031cd367343b9730dd5L44-R79) `currentPath` and `currentHash` to extract the current route path and hash
- Introduced the [getVersionedPath method](diffhunk://#diff-8ed94555eb24b9ab6404a3aab081d222da017446d39cf031cd367343b9730dd5L44-R79) to determine the correct path for the selected version, considering API prefix requirements
- Refactored the [switchVersion …
=> fix: preserve current page path when switching versions

docs-site/content/28.0/api/search.md
- add tip explaining Typesense uses offset-based pagination
- reference `page` and `per_page` parameters for pagination control
- include link to pagination parameters section
=> docs: add pagination tip to search API documentation

docs-site/content/.vuepress/components/TypesenseSearchBox.vue
Adds ⌘+K (Cmd+K/Ctrl+K) keyboard shortcut to focus the search box in the docs.
1. **In `TypesenseSearchBox.vue`**:
- Added keyboard shortcut support (⌘+K/Ctrl+K) to quickly focus the search input
- Added visual shortcut indicator in the UI to improve discoverability
1. **In `TypesenseSearchBox.vue`**:
- Added `handleKeyDown` event listener to detect ⌘+K/Ctrl+K keypress
- Implemented event listener cleanup in `beforeDestroy` lifecycle hook
- Updated the `update` method to include the shortcut indicator
- Added CSS styling for the new shortcut indicator
- This change improves user experience by adding a common keyboard shortcut pattern found in modern documentation sites and applications
=> feat(search): add keyboard shortcut to focus search input

docs-site/content/28.0/api/curation.md
- Add explanation of how override rules work with scoped API keys
- Include information about filter string format when combining requests
- Provide example of combined filter string construction
=> docs(curation): add section on overrides with scoped API keys

docs-site/content/guide/tips-for-filtering.md
- Add new "Filtering for Empty Fields" section to address user feedback
- Provide examples for using alphanumeric placeholders (~~)
- Document how to use `symbols_to_index` to filter with symbol placeholders
- Include code samples for schema configuration and preprocessing
- Add tip about choosing appropriate placeholders
=> docs: add section about filtering for empty fields

docs-site/content/28.0/api/stemming.md
- expand tip section to provide clearer explanation of stemming options
- add numbered list explaining different configuration scenarios
- clarify that `stem_dictionary` implies `stem: true` by default
- add explanation of how both stemming approaches work together
=> docs(stemming): improve explanation of stemming configuration options

docs-site/content/28.0/api/conversational-search-rag.md
- update `MultiSearch` tip section to explain that only one conversation object is returned
- clarify that this behavior is by design and intentional
- explain that results from all collections are used to generate a single comprehensive answer
=> docs(convo-search): clarify behavior of multiple conversations in multisearch

docs-site/content/guide/tips-for-filtering.md
- add section explaining why filters can sometimes return more results
- describe how typesense handles typo tolerance with filters
- provide guidance on controlling this behavior with `max_candidates`
=> docs(filtering): explain filtering behavior that can return more results

docs-site/README.md, typesense.org-v3/utils/index.ts, typesenseVersions.json
- Fixed by converting the commonJS file `typesenseVersions.js` to JSON so that both ES6 and CJS can import
=> fix error importing `typesenseLatestVersion` in Nuxt

docs-site/content/guide/faqs.md
- Add new FAQ section explaining why filters can sometimes return more results
- Describe how Typesense handles typo tolerance with filters
- Include example JSON showing how to control behavior with `max_candidates`
- Add link to detailed explanation in filtering documentation
=> docs(faqs): add explanation about filtering behavior returning more results

docs-site/content/guide/docsearch.md
- Add instructions for generating required `sitemap.xml` file
- Include steps to install and configure `@docusaurus/plugin-sitemap`
- Add build and serve commands for local testing
- Clarify requirement of having Typesense server running before scraper
=> docs(docsearch): add prerequisites for docusaurus sites in docsearch

docs-site/content/guide/syncing-data-into-typesense.md
Adds [Sequin](https://sequinstream.com/) as an option for easily replicating Postgres into TypeSense. It also removes Prisma Pulse since that product is no longer available.
- [ x ] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).
=> Add Sequin to the sync real-time changes docs

docs-site/content/28.0/api/documents.md
Add a warning about the maximum size of JSONL files (10GB)
=> docs(imports): add note about max size of doc import

docs-site/content/guide/tips-for-filtering.md
Adds a simple example for filtering on fields with a non-empty value.
=> docs(filtering): add example for filtering on non-empty fields

docs-site/content/28.0/api/analytics-query-suggestions.md
Hi @kishorenc and @jasonbosco,
I've been using Typesense regularly in both personal and client projects. It's been an amazing tool! I wanted to give back a little, so I’ve added some Python code snippets to the documentation to help others get started more easily.
Here’s a summary of the changes:
Add python code snippets for file in docs-site\content\28.0\api\analytics-query-suggestions.md
=> fix: add Python examples for analytics query suggestions v28

docs-site/content/28.0/api/joins.md
Mention that async referencing is not available in nested objects.
=> docs(joins): mention async refs inside objs

docs-site/content/29.0/api/README.md
This pull request updates the `README.md` file in the `docs-site/content/29.0/api` directory to improve formatting consistency for encoded references. The changes ensure that all encoded references are properly formatted as hyperlinks with square brackets.
Formatting consistency improvements:
* Updated encoded references for new features, including `Natural Language Search`, `Dynamic Sorting in Overrides`, and `Filter for two properties within a nested object array`, to use square brackets around PR numbers.
* Corrected encoded references for enhancements, such as `Support fetching reference fields in the GET document API`, to follow the same hyperlink formatting convention.
=> fix(api-readme): fix syntax for parentheses inside link on nl search

docs-site/content/guide/github-actions.md
Previously we're using `sleep 1 && curl http://localhost:8108/health` which is cumbersome, especially if the runner is not done on starting a service (what if it took `x` seconds before operational?).
In this change, we're improving the use of curl by adding a simple counter with timeouts (30s) as health checks and prints how long before operational.
Also, bumping typesense-version coverage for this example workflow file
=> Update github-actions.md to improve the use of curl-ing as health checks

docs-site/content/guide/install-typesense.md
The api key must be provided to the /debug endpoint. Only the /health endpoint doesn't require this,
as documented at https://typesense.org/docs/guide/data-access-control.html#managing-access-to-data .
Without the api key, you will see an error message:
```
$ curl http://localhost:8108/debug
{"message": "Forbidden - a valid `x-typesense-api-key` header must be sent."}
```
- update /debug endpoint example so it works
- add link to data access control docs about api keys
=> Fix debug api endpoint example in install guide

docs-site/content/29.0/api/vector-search.md
Add a small section for mentioning how to interact with different vector parameters on both autogeneration and manual embedding vector search
=> docs(vector-search): add section for using auto generated vs manual embeddings

docs-site/content/guide/tips-for-filtering.md
Fix: Types from example JSON schema. Inside object[], all fields types are arrays.
=> fix: fields inside object[] are arrays
