typesense/typesense-website

typesense.org/_config.yml, typesense.org/docs/0.9.1/api.html.md, typesense.org/docs/0.9.1/guide.html.md, typesense.org/downloads.html.md
No major changes to the documentation since this is a bug fix release.
=> Update docs for v9.0.1.

typesense.org/docs/0.11.2/guide.html
experyment was not changed across example code snippets from harry potter
=> Fix typo about typos

typesense.org/docs/0.16.0/guide.html
Delimiter comes before string in `explode()`.
=> Fix PHP example for adding books.

typesense.org/docs/0.18.0/api.html
Added the missing commas in search params which caused issues when copying the code.
=> Typos  | Missing commas in search params

typesense.org/algolia-vs-elasticsearch-vs-meilisearch-vs-typesense.html.md
I think this is what you meant. Great summary!
=> Correct typo on comparison page: export -> expert

new-site/docs-site/content/0.19.0/guide/typesense-firebase.md
Moving details about `id` filed to create collections section.
=> Fixing ID section

docs-site/content/0.19.0/guide/firebase-full-text-search.md
added brackets to collections function
=> collections is a function

docs-site/content/0.19.0/api/api-keys.md, docs-site/content/0.19.0/api/cluster-operations.md, docs-site/content/0.19.0/api/collections.md, docs-site/content/0.19.0/api/curation.md, docs-site/content/0.19.0/api/documents.md, docs-site/content/0.19.0/api/synonyms.md
- Add missing semicolons
- Fix code that is not PHP
=> Fix PHP code.

docs-site/content/0.20.0/api/documents.md
=> Fixed code snippet

docs-site/content/0.20.0/api/collections.md
Update value of `default_sorting_field`.
=> Update `List all collections` example.

docs-site/content/0.12.0/api/curation.md, docs-site/content/0.13.0/api/curation.md, docs-site/content/0.14.0/api/curation.md, docs-site/content/0.15.0/api/curation.md, docs-site/content/0.16.0/api/curation.md, docs-site/content/0.16.1/api/curation.md, docs-site/content/0.17.0/api/curation.md, docs-site/content/0.18.0/api/curation.md, docs-site/content/0.19.0/api/curation.md, docs-site/content/0.20.0/api/curation.md
=> Fixed list all overrides - js snippet

docs-site/content/0.20.0/api/synonyms.md
=> Update response. (#68)

docs-site/content/0.20.0/api/synonyms.md
=> Update collection in `Delete a synonym` example.

docs-site/content/0.20.0/api/synonyms.md
Update `One-way synonym` bash command.
Update `Retrieve a synonym` bash command.
=> Update bash commands in `Synonyms`.

docs-site/content/0.20.0/api/documents.md
=> Update shell command

.gitignore, docs-site/content/0.20.0/api/collections.md, docs-site/yarn.lock
Add Dart examples for Collections.
Ignore .yarn
=> Dart examples.

.gitignore, docs-site/content/0.20.0/api/collections.md, docs-site/yarn.lock
Reverts typesense/typesense-website#78
=> Revert "Dart examples."

.gitignore, docs-site/content/0.20.0/api/api-keys.md, docs-site/content/0.20.0/api/cluster-operations.md, docs-site/content/0.20.0/api/collection-alias.md, docs-site/content/0.20.0/api/collections.md, docs-site/content/0.20.0/api/curation.md, docs-site/content/0.20.0/api/documents.md, docs-site/content/0.20.0/api/synonyms.md, docs-site/yarn.lock
Ignore .yarn/
Update yarn.lock
Add Collections dart examples.
Add Documents dart examples.
Add Keys dart examples.
Add Curation dart examples.
Add Alias dart examples.
Add Synonyms dart examples.
Add Cluster Operations dart examples.
[related](https://github.com/typesense/typesense-dart/issues/68)
=> Add dart Examples.

docs-site/content/0.20.0/api/authentication.md
=> Add Authentication dart examples.

docs-site/content/0.21.0/api/authentication.md, docs-site/content/0.21.0/api/documents.md
Add Authentication dart example to v0.21.0
Add Geosearch dart example to v0.21.0
Update search radius to 5.1
Add sample response to Geosearch.
=> Geosearch and v0.21.0 dart examples

docs-site/content/0.21.0/api/authentication.md, docs-site/content/0.21.0/api/documents.md, docs-site/content/0.21.0/api/synonyms.md
=> Update docs 22 jul 2021

docs-site/content/0.20.0/api/api-clients.md, docs-site/content/0.21.0/api/api-clients.md
=> Add dart client instructions.

docs-site/content/0.21.0/guide/mongodb-full-text-search.md
=> update: mongodb blog

docs-site/content/0.21.0/api/api-clients.md
=> Rename Symphony to its proper name Symfony

typesense.org/components/Home/SectionFeatureList.vue
description:
'Provide more varietry in your results by grouping results. 
<----------->
Changed To
<----------->
description:
'Provide more variety in your results by grouping results.
Typo fixed & solved #98
=> Fixed Typo in Grouping & Distinct Feature Desc

docs-site/content/guide/building-a-search-application.md
Consuming the stream by line results in Typesense API timeouts. It'd be better to show the `import` method along with the `batch` parameter.
=> use the `import` with a batch size

docs-site/content/guide/building-a-search-application.md
=> resolve some typos

docs-site/content/guide/docsearch.md
Changed
`one of those as templates`
to
`one of those as a template`
=> Improve grammar

docs-site/content/guide/install-typesense.md
Add install instructions for windows WSL
=> Add windows WSL install instructions

docs-site/content/guide/mongodb-full-text-search.md
Removing an unknown variable "pipeline" and removing a hard-coded API key with a generic placeholder from the snippet above.
=> Minor corrections

docs-site/content/guide/docker-swarm-high-availability.md, docs-site/yarn.lock
…placement constraints
- add `docker swarm join-token worker` command in the documentation 
- add node.hostname in the docker-stack.yml to tie typesense service to a node
=> Add join token command in documentation and introduce node name in docker-stack.yml

docs-site/content/guide/install-typesense.md
=> fix typo on documentation

docs-site/content/guide/install-typesense.md
=> Fix file path

docs-site/content/0.17.0/api/documents.md, docs-site/content/0.18.0/api/documents.md, docs-site/content/0.19.0/api/documents.md, docs-site/content/0.20.0/api/documents.md, docs-site/content/0.21.0/api/documents.md, docs-site/content/0.22.0/api/documents.md, docs-site/content/0.22.1/api/documents.md, docs-site/content/0.22.2/api/documents.md, docs-site/content/0.23.0/api/documents.md, docs-site/content/0.23.1/api/documents.md
Changed the doc for how to convert csv to jsonl (JSON Lines) with `mlr` version 6
=> Update miller script for converting csv to jsonl

docs-site/content/overview/use-cases.md
- Added Typesense Github Actions cookbook
=> Add github action cookbook

docs-site/content/0.23.1/api/curation.md
Added an example of how filtering interacts with `includes` on overrides.
=> Add curation plus filtering example

docs-site/content/0.23.0/api/collections.md
=> Dart update collection example.

docs-site/content/0.22.0/api/collections.md
=> Update create collection Dart example.

docs-site/content/0.24.0/api/api-clients.md, docs-site/content/0.24.0/api/collections.md
=> Update Dart examples.

typesense.org/pages/typesense-vs-algolia-vs-elasticsearch-vs-meilisearch.vue
Hey 👋,
Happy to propose this set of modifications. Could you take a look at it, please? I am happy to answer your questions and help to decide about anything by providing links, documentation, or anything else.
In this PR, I propose fixing the wrong statements about Meilisearch. As we worked a lot, we improved the engine and reduced most of the limitations.
=> Fix wrong statements about Meilisearch

docs-site/content/guide/search-ui-components.md
Port is type number and its query_by now
=> doc: port to number and queryBy to query_by

docs-site/content/0.24.0/api/api-keys.md
`documents:export` was missing for the document actions.
=> Update api-keys.md to include documents:export

docs-site/content/guide/docsearch.md
Option C example is missing a closing div.
=> Option C example close searchbar div

docs-site/content/0.24.0/api/vector-search.md, docs-site/content/0.24.1/api/vector-search.md
=> Add dart vector search examples.

docs-site/content/0.24.1/api/api-clients.md
As suggested by: https://twitter.com/jasonbosco/status/1658269187976880130
=> Add SEAL to api clients

docs-site/content/guide/docsearch.md
As requested in https://github.com/typesense/typesense-docsearch-scraper/pull/41#issuecomment-1562170285
Added some tips for common challenges when running the scraper inside Docker
=> [docs] Updated docsearch.md with common docker challenges

docs-site/content/0.24.1/api/api-clients.md
Added Elixir client library link to docs
=> Add Elixir client library link to docs

docs-site/content/0.24.0/api/search.md, docs-site/content/0.24.1/api/search.md, docs-site/content/0.25.0/api/search.md
=> Add dart examples for presets.

docs-site/content/0.25.0/api/vector-search.md
=> Add distance_threshold

docs-site/content/guide/docsearch.md
- Fixed a typo
- Replaced -- with proper emdashes
=> [chore] Typo fixes in docsearch.md

docs-site/content/0.25.0/api/api-clients.md
Add Typesense-Dashboard as utility app
=> Update api-clients.md with GUI app

docs-site/content/guide/docsearch.md
=> Added environment variables for Basic HTTP authentication

docs-site/content/0.25.1/api/search.md
Fixing a broken section link in the docs.
=> Fix section reference

docs-site/content/0.23.0/api/collections.md, docs-site/content/0.23.1/api/collections.md, docs-site/content/0.24.0/api/collections.md, docs-site/content/0.24.1/api/collections.md, docs-site/content/0.25.0/api/collections.md, docs-site/content/0.25.1/api/collections.md
Add commas to Fix Bad JSON on the example under Modifying an existing field on the Collections page.
=> Fix Bad JSON on the example

docs-site/content/.vuepress/config.js, docs-site/content/guide/reference-implementations/guitar-chords-search-in-different-js-frameworks.md
=> Add Guitar Chords Search in different JS frameworks into reference-implementations

docs-site/content/0.25.2/api/README.md
Update links on the 0.25.2 README to point to the 0.25.2 documentation.
=> Update links to point to 0.25.2

docs-site/content/guide/building-a-search-application.md
=> Fix typo on building-a-search-application.md

docs-site/content/26.0/api/joins.md
=> Correct typo’s

docs-site/content/26.0/api/joins.md
=> Add Left join section

docs-site/content/guide/supabase-full-text-search.md
=> fix typo in supabase docs

docs-site/content/26.0/api/vector-search.md
=> Fix default values for HNSW params

docs-site/content/guide/syncing-data-into-typesense.md
This pull request adds a new subsection titled "Using Prisma Pulse" to the "Syncing Data into Typesense" section of the Typesense documentation. The purpose of this addition is to provide guidance on how Typesense users can effectively manage real-time data synchronization using Prisma Pulse.
The new subsection includes the following:
- A brief introduction to Prisma Pulse, explaining its purpose and benefits for real-time data syncing with Typesense.
- A "Setup at a glance" section that outlines the prerequisites and steps needed to integrate Prisma Pulse with Typesense.
- A code example demonstrating how to use Prisma Pulse's .stream() API to listen for database changes and sync them to Typesense collections in real-time.
=> docs: added Prisma Pulse to sync real-time changes

docs-site/content/26.0/api/conversational-search-rag.md
=> Update conversational-search-rag.md for vLLM

docs-site/content/0.17.0/api/api-keys.md
Fixes example code by adding closing brackets.
- [S] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).
=> fix(docs): close brackets in scoped api key docs

docs-site/content/guide/organizing-collections.md
Correct misspelled word in documentation page organizing-collections.md
=> Fix typo in organizing-collections.md

docs-site/content/.vuepress/config.js, docs-site/content/guide/reference-implementations/joins.md
Adds a page about the JOINs demo in the reference implementations section
=> docs: add joins reference implementation page

docs-site/content/26.0/api/joins.md
=> Add info about `id: *` filter.

docs-site/content/26.0/api/joins.md
=> Add _eval reference collection sort_by example.

docs-site/content/26.0/api/joins.md
=> Add note about adding reference field using alter collection.

docs-site/content/0.25.0/api/documents.md
Updated the sample response in the documentation for the update by query request to accurately reflect the actual response from TS.
=> Docs: Update sample response for the update by query request

docs-site/content/26.0/api/analytics-query-suggestions.md
Adding this note because I had to dig through the [code](https://github.com/typesense/typesense/blob/9b6894fee642d8f5fa6dd067ed7651ffdc043d09/src/collection_manager.cpp#L1908) to figure this out.
=> doc: add analytics query type note

docs-site/content/26.0/api/stopwords.md
Change JSON field `name` to `id`
=> Update stopwords.md: fix example upsert response

docs-site/content/27.0/api/conversational-search-rag.md
=> Update conversational-search-rag.md fix CF worker AI namespace

docs-site/content/27.0/api/search.md
Add a simple code example for upserting presets using the Javascript client
=> docs(presets): add code examples for javascript

docs-site/content/27.1/api/vector-search.md
Add a table for showcasing all possible vector query parameters, to consolidate them all into a single place.
=> docs(vector-search): add table for vector search parameters

docs-site/content/27.1/api/documents.md
=> [TASK] Fix PHP example

docs-site/content/27.1/api/vector-search.md
=> Update vector-search.md: fix typo

docs-site/content/.vuepress/config.js, docs-site/content/guide/reference-implementations/nextjs-app-router-ssr.md
Add an example implementation using Next.js' App Router with server-side rendering
=> Add Next.js App Router SSR example

docs-site/content/.vuepress/config.js, docs-site/content/guide/natural-language-search.md
=> docs(cookbooks): Natural Language Search

docs-site/content/guide/natural-language-search.md
=> docs(cookbooks): Natural Language Search update to Genkit v0.9

docs-site/content/27.1/api/api-clients.md
Added another Laravel integration to the list
=> Added another Laravel integration

docs-site/content/28.0/api/vector-search.md
=> fix: vector-search.md

docs-site/content/28.0/api/documents.md, docs-site/content/guide/syncing-data-into-typesense.md
This pull request includes updates to the documentation to provide guidance on handling high-volume writes in Typesense. The changes introduce a new section on using buffer tables or queuing systems to optimize performance and ensure efficient data synchronization.
Documentation updates:
* [`docs-site/content/28.0/api/documents.md`](diffhunk://#diff-8826b26b28ad6a54ee04f5782b21df9efc13fc96734e9d9b0336974ba06c98f3R343-R346): Added a tip about using buffer tables or queuing systems for applications that need to handle more than 10s of writes-per-second.
* [`docs-site/content/guide/syncing-data-into-typesense.md`](diffhunk://#diff-f2da4fa16915d860b1887ae15e73c940fcee4aa3f634f2932ec177fecb49b924R56-R100): Added a detailed guide on handling high-volume writes, including creating a buffer …
=> docs: add high-volume writes guidance and optimization tips

docs-site/content/28.0/api/stemming.md
https://typesense-community.slack.com/archives/C01P749MET0/p1740646472051239
=> Fix custom pre-made English plurals dictionary link

docs-site/content/28.0/api/joins.md
=> Add info about `strategy: nest_array` in `Many-to-many relation` section.

docs-site/content/28.0/api/api-clients.md
Broken link to the llama index example
=> Fix llama index doc link

docs-site/content/28.0/api/image-search.md
Update image search docs with embedding both text and image example
=> Update image search docs

docs-site/content/28.0/api/federated-multi-search.md
=> Update Union section

docs-site/content/guide/high-availability.md
- add guidance for single node recovery process
- explain when to use snapshot restore for disaster recovery
- provide step-by-step instructions for both scenarios
=> docs(ha): add node recovery section to high-availability guide

typesense.org-v3/pages/typesense-vs-algolia-vs-elasticsearch-vs-meilisearch.vue
=> Update comparison table

typesense.org-v3/components/Navbar.vue
Improved navbar responsiveness with container layout, better spacing and refined button styles.
1. **In `Navbar.vue`**:
- Added container-based layout with `container mx-auto` class
- Set specific width constraints: `md:w-[95%]` and `xl:max-w-6xl`
- Added subtle elevation with `md:shadow-lg md:shadow-black/20`
1. **In `Navbar.vue`**:
- Adjusted padding on main navbar container
- Fixed rounded corners with proper `rounded-b-3xl` class
- Improved spacing between navigation items with responsive gaps
- Set specific `md:pb-8` padding for medium screens
1. **Quick Start Button in `Navbar.vue`**:
- Improved container alignment with `flex h-full items-center justify-end`
- Made button text size responsive: `text-xs` and `lg:text-sm`
- Replaced static shadow with hover effect using …
=> Navbar Responsive Design Enhancements

docs-site/content/guide/tips-for-filtering.md
Fix _not-a-member-of_ operator from `!=[]` to `![]`
=> docs(filtering): fix not-a-member of operator

typesense.org-v3/components/AnnouncementBanner.vue
Fixed invisible announcement banner still clickable
=> fix: disable pointer events when hiding AnnouncementBanner

typesense.org-v3/components/Home/SectionSearchUIIntegration.vue
=> typesense.org-v3: fixed card width on large screen

docs-site/content/guide/install-typesense.md
Found another great operator by @akyriako and other contributors so thought it would be great to add it as another option for people during installation.
=> Adding additional Kubernetes Community Operator

docs-site/content/28.0/api/api-clients.md
llama-index link change to /docs/docs
=> llama-index link change to /docs/docs

docs-site/content/28.0/api/api-clients.md
As requested in https://github.com/Siege-Software/django-typesense/issues/102
=> Add Siege-Software/django-typesense

docs-site/content/overview/comparison-with-alternatives.md
=> typo - Update comparison-with-alternatives.md

docs-site/content/guide/faqs.md
Update the docs to include the newest union search feature when aggregating results from more than one collection
=> docs(faqs): add union search feature for federated search

docs-site/content/28.0/api/api-clients.md
Added community MCP Servers for typesense
=> chore: added mcp servers from community

docs-site/content/29.0/api/curation.md
- Add dynamic sorting overview and schema example
- Add code examples for query-based dynamic sorting across all languages
- Add code examples for filter-based dynamic sorting across all languages
- Add note about proper field indexing for dynamic sorting
=> docs(curation): add dynamic sorting section to overrides

docs-site/content/29.0/api/conversational-search-rag.md
- Add azure openai to supported llm platforms list
- Add azure tab to conversational model creation examples
- Add azure openai curl example with endpoint url configuration
- Update parameters table to include azure openai and url parameter
=> docs(conversational-search): add azure openai support

docs-site/content/29.0/api/vector-search.md
Match the example in [#2176](https://github.com/typesense/typesense/pull/2176)
=> docs(vector): refactor docs to give example for azure-based embeddings

docs-site/content/29.0/api/server-configuration.md
added default values for rockdb params
=> chore(server params): added rockdb defaults

docs-site/content/29.0/api/vector-search.md
Mention [#2281](https://github.com/typesense/typesense/pull/2281)
=> docs(rag): add openai path example

docs-site/content/29.0/api/api-clients.md
=> AnnexUI inclusion

docs-site/content/30.0/api/analytics-query-suggestions.md, docs-site/content/30.0/api/curation.md, docs-site/content/30.0/api/synonyms.md
=> add: v30 curation docs
